settings:
  title: 'Mirror Status Page'
  url: 'https://status.unblock.my.id' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: 'Some checks failed'

monitors:
  - id: nhentai.unblock.my.id
    name: nHentai
    description: 'nHentai Mirror.'
    url: 'https://nhentai.unblock.my.id/'
    method: GET
    expectStatus: 200

  - id: hentaicafe.unblock.my.id
    name: Hentai Cafe
    description: 'Hentai Cafe Mirror.'
    url: 'https://hentaicafe.unblock.my.id/'
    method: GET
    expectStatus: 200

  - id: e-hentai.unblock.my.id
    name: E-hentai
    description: 'E-Hentai Mirror'
    url: 'https://e-hentai.unblock.my.id/'
    method: GET
    expectStatus: 200
