settings:
  title: 'Status Page'
  url: 'https://status.unblock.my.id' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: 'Some checks failed'

monitors:
  - id: nhentai
    name: nhentai Mirror
    description: 'nHentai Mirror.'
    url: 'https://nhentai.unblock.my.id/'
    method: GET
    expectStatus: 200

  - id: hentaicafe
    name: Hentai Cafe Mirror
    description: 'Hentai Cafe Mirror.'
    url: 'https://hentaicafe.unblock.my.id'
    method: GET
    expectStatus: 200

  - id: ehentai
    name: e-hentai Mirror
    desc: 'E-Hentai Mirror'
    url: 'https://e-hentai.unblock.my.id/'
    method: GET
    expectStatus: 200
